name: map_overlay
description: An easy to use, widget based, map overlay plugin.
version: 0.0.1
author: Lachlan van der Velden <me@lachlanvelden.com>
homepage: https://github.com/coman3/flutter_map_overlay

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^1.2.0
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
